// examples/solid-basic/src/App.tsx
import { createSignal } from 'solid-js';

export function App() {
  const [count, setCount] = createSignal(0);

  return (
    <div style="font-family: sans-serif; padding: 2rem; text-align: center;">
      <h1>SolidJS Basic App with Ray</h1>
      <button onClick={() => setCount(count() + 1)}>
        Count: {count()}
      </button>
    </div>
  );
}

// packages/create-ray/templates/vue-ts/src/App.vue
<template>
  <div style="padding: 2.5rem; font-family: sans-serif; text-align: center;">
    <h1>Welcome to {{projectName}} on Ray</h1>
    <HelloWorld msg="Vue 3 SFC + TypeScript on Ray" />
  </div>
</template>

<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue';
</script>
