// examples/vue-basic/src/Counter.vue
<template>
  <div class="counter">
    <p>Count: {{ count }}</p>
    <button @click="increment">Increment</button>
  </div>
</template>

<script>
export default {
  data() {
    return {
      count: 0,
    };
  },
  methods: {
    increment() {
      this.count++;
    },
  },
};
</script>

<style>
.counter {
  margin-top: 10px;
}
button {
  padding: 8px 16px;
  cursor: pointer;
}
</style>

// examples/react-mdx/src/components/Counter.tsx
import React, { useState } from 'react';

export function Counter() {
  const [count, setCount] = useState(0);

  return (
    <button
      onClick={() => setCount(c => c + 1)}
      style={{
        padding: '0.5rem 1rem',
        borderRadius: '6px',
        background: '#6366f1',
        color: '#fff',
        border: 'none',
        cursor: 'pointer',
        fontWeight: 'bold',
      }}
    >
      Count: {count}
    </button>
  );
}
