// examples/solid-basic/src/App.tsx
import { createSignal } from 'solid-js';

export function App() {
  const [count, setCount] = createSignal(0);

  return (
    <div style="font-family: sans-serif; padding: 2rem; text-align: center;">
      <h1>SolidJS Basic App with Ray</h1>
      <button onClick={() => setCount(count() + 1)}>
        Count: {count()}
      </button>
    </div>
  );
}

// examples/svelte-basic/src/App.svelte
<script>
  let count = 0;
  function increment() {
    count += 1;
  }
</script>

<main>
  <h1>Svelte Basic App with Ray</h1>
  <button on:click={increment}>Count: {count}</button>
</main>

<style>
  main {
    font-family: sans-serif;
    text-align: center;
    padding: 2rem;
  }
  button {
    padding: 0.5rem 1rem;
    font-size: 1rem;
    cursor: pointer;
  }
</style>
